# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, help_text='Minimum order amount required to activate this discount', max_digits=10)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, help_text='Bonus percentage applied when condition is met', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conditional_discount',
                'ordering': ['-minimum_purchase_amount'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy Policies',
                'db_table': 'privacy_policy',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BDM', max_length=100)),
                ('logo', models.ImageField(default='logos/logo.png', upload_to='logos/')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('description', models.TextField(default='A platform for managing orders.')),
                ('delivery_charge', models.DecimalField(decimal_places=1, default=80.0, max_digits=10)),
                ('contact_email', models.EmailField(default='info@bdm.com', max_length=254)),
                ('contact_phone', models.CharField(default='1234567890', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
