# Generated by Django 6.0.2 on 2026-06-19 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Human version, e.g. 1.2.0', max_length=20)),
                ('version_code', models.PositiveIntegerField(help_text='Numeric build code used for comparison, e.g. 12. Higher = newer.')),
                ('apk', models.FileField(upload_to='apks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=False, help_text='When on, this release is offered to app users.')),
                ('force_update', models.BooleanField(default=False, help_text='When on, the app should require updating to this build.')),
                ('file_size', models.BigIntegerField(default=0, help_text='APK size in bytes (auto).')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_release',
                'ordering': ['-version_code', '-created_on'],
            },
        ),
        migrations.AddField(
            model_name='siteinfomodel',
            name='maintenance_message',
            field=models.CharField(blank=True, default='We are currently under maintenance. Please check back soon.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteinfomodel',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
