# Generated by Django 6.0.2 on 2026-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_apprelease_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
