# Generated by Django 6.0.2 on 2026-07-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_termsandconditions_id'),
        ('settings', '0004_siteinfomodel_whatsapp_number'),
    ]

    operations = [
    ]
