from rest_framework import serializers

from orders.models import Order, ReturnItem
from .models import DepositRequest, ReturnRequest, ReturnRequestItem


class ReturnedProductSerializer(serializers.ModelSerializer):
    """A finalized returned product (orders.ReturnItem) for the agent's orders —
    includes returns generated by admin order edits, not just app submissions."""

    invoice_number = serializers.CharField(source="order.invoice_number", read_only=True)
    shop_name = serializers.SerializerMethodField()
    product_name = serializers.SerializerMethodField()
    line_total = serializers.SerializerMethodField()
    created_by_name = serializers.SerializerMethodField()
    source = serializers.SerializerMethodField()

    class Meta:
        model = ReturnItem
        fields = [
            "id", "order", "invoice_number", "shop_name",
            "product", "product_name", "quantity", "unit_price", "line_total",
            "reason", "created_by", "created_by_name", "source", "created_on",
        ]

    def get_shop_name(self, obj):
        return getattr(obj.order.user_id, "shop_name", None) if obj.order and obj.order.user_id else None

    def get_product_name(self, obj):
        return getattr(obj.product, "product_name", None) if obj.product else None

    def get_line_total(self, obj):
        return float((obj.unit_price or 0) * obj.quantity)

    def get_created_by_name(self, obj):
        return getattr(obj.created_by, "full_name", None) if obj.created_by else None

    def get_source(self, obj):
        # ReturnItems created by admin order-edits have no created_by; agent
        # (confirmed-request) returns record the delivery agent who triggered them.
        return "agent" if obj.created_by_id else "admin"


class ReturnRequestItemSerializer(serializers.ModelSerializer):
    product_name = serializers.SerializerMethodField()
    line_total = serializers.SerializerMethodField()

    class Meta:
        model = ReturnRequestItem
        fields = ["id", "product", "product_name", "quantity", "unit_price", "line_total", "reason"]

    def get_product_name(self, obj):
        return getattr(obj.product, "product_name", None) if obj.product else None

    def get_line_total(self, obj):
        return float(obj.quantity * (obj.unit_price or 0))


class ReturnRequestSerializer(serializers.ModelSerializer):
    items = ReturnRequestItemSerializer(many=True, read_only=True)
    delivery_man_name = serializers.SerializerMethodField()
    reviewed_by_name = serializers.SerializerMethodField()
    invoice_number = serializers.CharField(source="order.invoice_number", read_only=True)
    shop_name = serializers.SerializerMethodField()
    total_quantity = serializers.SerializerMethodField()
    total_value = serializers.SerializerMethodField()

    class Meta:
        model = ReturnRequest
        fields = [
            "id", "order", "invoice_number", "shop_name",
            "delivery_man", "delivery_man_name", "status", "note",
            "created_at", "reviewed_by", "reviewed_by_name", "reviewed_at", "review_note",
            "total_quantity", "total_value", "items",
        ]

    def get_delivery_man_name(self, obj):
        return getattr(obj.delivery_man, "full_name", None) if obj.delivery_man else None

    def get_reviewed_by_name(self, obj):
        return getattr(obj.reviewed_by, "full_name", None) if obj.reviewed_by else None

    def get_shop_name(self, obj):
        return getattr(obj.order.user_id, "shop_name", None) if obj.order and obj.order.user_id else None

    def get_total_quantity(self, obj):
        return sum(i.quantity for i in obj.items.all())

    def get_total_value(self, obj):
        return float(sum(i.quantity * (i.unit_price or 0) for i in obj.items.all()))


class DepositRequestSerializer(serializers.ModelSerializer):
    delivery_man_name = serializers.SerializerMethodField()
    reviewed_by_name = serializers.SerializerMethodField()
    payment_count = serializers.SerializerMethodField()

    class Meta:
        model = DepositRequest
        fields = [
            "id",
            "delivery_man",
            "delivery_man_name",
            "amount",
            "status",
            "note",
            "requested_at",
            "reviewed_by",
            "reviewed_by_name",
            "reviewed_at",
            "review_note",
            "payment_count",
        ]

    def get_delivery_man_name(self, obj):
        return getattr(obj.delivery_man, "full_name", None) if obj.delivery_man else None

    def get_reviewed_by_name(self, obj):
        return getattr(obj.reviewed_by, "full_name", None) if obj.reviewed_by else None

    def get_payment_count(self, obj):
        return obj.payments.count()


class DeliveryOrderSerializer(serializers.ModelSerializer):
    """Compact order view for the delivery app's order list."""

    shop_name = serializers.SerializerMethodField()
    customer_name = serializers.SerializerMethodField()
    phone = serializers.SerializerMethodField()
    address = serializers.CharField(source="shipping_address", read_only=True)
    area = serializers.SerializerMethodField()
    invoice_amount = serializers.FloatField(source="total_amount", read_only=True)
    collected_amount = serializers.FloatField(read_only=True)
    due_amount = serializers.FloatField(read_only=True)
    payment_status = serializers.SerializerMethodField()
    delivery_status = serializers.CharField(source="order_status", read_only=True)
    assigned_to_name = serializers.SerializerMethodField()
    shop_latitude = serializers.SerializerMethodField()
    shop_longitude = serializers.SerializerMethodField()

    class Meta:
        model = Order
        fields = [
            "order_id",
            "invoice_number",
            "shop_name",
            "customer_name",
            "phone",
            "address",
            "area",
            "shop_latitude",
            "shop_longitude",
            "invoice_amount",
            "collected_amount",
            "due_amount",
            "payment_status",
            "delivery_status",
            "assigned_to",
            "assigned_to_name",
            "order_date",
        ]

    def get_assigned_to_name(self, obj):
        return getattr(obj.assigned_to, "full_name", None) if obj.assigned_to else None

    def get_shop_name(self, obj):
        return getattr(obj.user_id, "shop_name", None) if obj.user_id else None

    def get_customer_name(self, obj):
        return getattr(obj.user_id, "full_name", None) if obj.user_id else None

    def get_phone(self, obj):
        return getattr(obj.user_id, "phone", None) if obj.user_id else None

    def get_area(self, obj):
        user = obj.user_id
        return getattr(user.area, "area_name", None) if user and user.area else None

    def get_shop_latitude(self, obj):
        v = getattr(obj.user_id, "latitude", None) if obj.user_id else None
        return float(v) if v is not None else None

    def get_shop_longitude(self, obj):
        v = getattr(obj.user_id, "longitude", None) if obj.user_id else None
        return float(v) if v is not None else None

    def get_payment_status(self, obj):
        total = float(obj.total_amount or 0)
        collected = float(obj.collected_amount or 0)
        if collected <= 0:
            return "Due"
        if collected < total:
            return "Partial"
        return "Paid"


class DeliveryOrderItemSerializer(serializers.Serializer):
    """An order line as seen by the agent app (for delivery + return selection)."""
    product = serializers.IntegerField(source="product_id")
    product_name = serializers.SerializerMethodField()
    quantity = serializers.IntegerField()
    unit_price = serializers.FloatField()
    mrp = serializers.FloatField()
    discount_percent = serializers.FloatField()
    line_total = serializers.SerializerMethodField()

    def get_product_name(self, obj):
        return obj.product_name or (obj.product.product_name if obj.product else None)

    def get_line_total(self, obj):
        return float((obj.unit_price or 0) * obj.quantity)


class DeliveryOrderDetailSerializer(DeliveryOrderSerializer):
    """Compact order view + its line items (used by the agent order-detail endpoint)."""
    items = DeliveryOrderItemSerializer(many=True, read_only=True)

    class Meta(DeliveryOrderSerializer.Meta):
        fields = DeliveryOrderSerializer.Meta.fields + ["items"]
